# Generated by Django 6.1.1 on 2026-07-26 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MusicBrainzArtist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('artist_name', models.CharField(max_length=255)),
                ('music_brainz_id', models.UUIDField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyTrack',
            fields=[
                ('serial_number', models.PositiveIntegerField(blank=True, null=True)),
                ('artist_name', models.CharField(max_length=100)),
                ('track_name', models.CharField(max_length=600)),
                ('track_id', models.CharField(max_length=22, primary_key=True, serialize=False)),
                ('popularity', models.PositiveSmallIntegerField()),
                ('year', models.PositiveSmallIntegerField()),
                ('genre', models.CharField(blank=True, max_length=50)),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.PositiveSmallIntegerField()),
                ('loudness', models.FloatField()),
                ('mode', models.PositiveSmallIntegerField()),
                ('speechiness', models.FloatField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('duration_ms', models.PositiveIntegerField()),
                ('time_signature', models.PositiveSmallIntegerField()),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='recommendations.musicbrainzartist')),
            ],
        ),
        migrations.CreateModel(
            name='MusicBrainzArtistTag',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=255)),
                ('tag_count', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='recommendations.musicbrainzartist')),
            ],
        ),
        migrations.CreateModel(
            name='SpotifyTrackEmbedding',
            fields=[
                ('track', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recommendations.spotifytrack')),
                ('danceability_norm', models.FloatField()),
                ('energy_norm', models.FloatField()),
                ('loudness_norm', models.FloatField()),
                ('mode_norm', models.FloatField()),
                ('speechiness_norm', models.FloatField()),
                ('acousticness_norm', models.FloatField()),
                ('instrumentalness_norm', models.FloatField()),
                ('liveness_norm', models.FloatField()),
                ('valence_norm', models.FloatField()),
                ('tempo_norm', models.FloatField()),
            ],
        ),
    ]
