# Generated by Django 6.1.1 on 2026-09-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_artist_tag_relationship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicbrainzartisttag',
            name='id',
            field=models.BigAutoField(
                auto_created=True,
                primary_key=True,
                serialize=False,
                verbose_name='ID',
            ),
        ),
    ]
